version: "3.1"

services:
  minecraft_server:
    container_name: minecraft
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '25565:25565'
    volumes:
      - ./:/minecraft
